on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: remote ssh test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    
    - name: executing remote ssh commands with ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al